# This will create a simple GitHub Pages site with the cayman theme
theme: jekyll-theme-cayman
title: This is the Title of the site
description: Description of the site
show_downloads: true
linkedin: "https://linkedin.com/in/planetoftheweb"
